name: "Thread Sensor Tag UPD 2 MQTT"
description: "My first real add-on!"
version: "1.0.38"
slug: "udp2mqtt"
init: false
host_network: true
logger:
  default: info
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  4141/udp: 4141
services:
  - mqtt:need