name: "Thread Sensor Tag UPD 2 MQTT"
description: "AddOn to translate the Thread Sensor Tag UDP pakets into Home Assistant Devices"
version: "1.1.0"
slug: "udp2mqtt"
init: false
image: "informatic0re/home-assistant-{arch}-sensor-tag-addon"
host_network: true
logger:
  default: info
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  4141/udp: 4141
services:
  - mqtt:need