name: "Test"

on: [push, pull_request]

env:
  VERSION: 1.0.0

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target . \
            --docker-hub home-assistant-sensor-tag-addon
